// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inference/inference/confirmation_poc_event.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ConfirmationPoCPhase defines the phases of a confirmation PoC event.
type ConfirmationPoCPhase int32

const (
	ConfirmationPoCPhase_CONFIRMATION_POC_INACTIVE     ConfirmationPoCPhase = 0
	ConfirmationPoCPhase_CONFIRMATION_POC_GRACE_PERIOD ConfirmationPoCPhase = 1
	ConfirmationPoCPhase_CONFIRMATION_POC_GENERATION   ConfirmationPoCPhase = 2
	ConfirmationPoCPhase_CONFIRMATION_POC_VALIDATION   ConfirmationPoCPhase = 3
	ConfirmationPoCPhase_CONFIRMATION_POC_COMPLETED    ConfirmationPoCPhase = 4
)

var ConfirmationPoCPhase_name = map[int32]string{
	0: "CONFIRMATION_POC_INACTIVE",
	1: "CONFIRMATION_POC_GRACE_PERIOD",
	2: "CONFIRMATION_POC_GENERATION",
	3: "CONFIRMATION_POC_VALIDATION",
	4: "CONFIRMATION_POC_COMPLETED",
}

var ConfirmationPoCPhase_value = map[string]int32{
	"CONFIRMATION_POC_INACTIVE":     0,
	"CONFIRMATION_POC_GRACE_PERIOD": 1,
	"CONFIRMATION_POC_GENERATION":   2,
	"CONFIRMATION_POC_VALIDATION":   3,
	"CONFIRMATION_POC_COMPLETED":    4,
}

func (x ConfirmationPoCPhase) String() string {
	return proto.EnumName(ConfirmationPoCPhase_name, int32(x))
}

func (ConfirmationPoCPhase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_02c46183d02e7335, []int{0}
}

// ConfirmationPoCEvent tracks a single confirmation PoC event during the inference phase.
// These events randomly trigger to verify that inference-serving nodes (POC_SLOT=false)
// maintain their computational capacity.
type ConfirmationPoCEvent struct {
	EpochIndex            uint64               `protobuf:"varint,1,opt,name=epoch_index,json=epochIndex,proto3" json:"epoch_index,omitempty"`
	EventSequence         uint64               `protobuf:"varint,2,opt,name=event_sequence,json=eventSequence,proto3" json:"event_sequence,omitempty"`
	TriggerHeight         int64                `protobuf:"varint,3,opt,name=trigger_height,json=triggerHeight,proto3" json:"trigger_height,omitempty"`
	GenerationStartHeight int64                `protobuf:"varint,4,opt,name=generation_start_height,json=generationStartHeight,proto3" json:"generation_start_height,omitempty"`
	GenerationEndHeight   int64                `protobuf:"varint,5,opt,name=generation_end_height,json=generationEndHeight,proto3" json:"generation_end_height,omitempty"`
	ValidationStartHeight int64                `protobuf:"varint,6,opt,name=validation_start_height,json=validationStartHeight,proto3" json:"validation_start_height,omitempty"`
	ValidationEndHeight   int64                `protobuf:"varint,7,opt,name=validation_end_height,json=validationEndHeight,proto3" json:"validation_end_height,omitempty"`
	Phase                 ConfirmationPoCPhase `protobuf:"varint,8,opt,name=phase,proto3,enum=inference.inference.ConfirmationPoCPhase" json:"phase,omitempty"`
	// Block hash from (generation_start_height - 1) for PoC nonce generation.
	// This hash is only set when transitioning to GENERATION phase to prevent
	// precomputation during the grace period.
	PocSeedBlockHash string `protobuf:"bytes,9,opt,name=poc_seed_block_hash,json=pocSeedBlockHash,proto3" json:"poc_seed_block_hash,omitempty"`
}

func (m *ConfirmationPoCEvent) Reset()         { *m = ConfirmationPoCEvent{} }
func (m *ConfirmationPoCEvent) String() string { return proto.CompactTextString(m) }
func (*ConfirmationPoCEvent) ProtoMessage()    {}
func (*ConfirmationPoCEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_02c46183d02e7335, []int{0}
}
func (m *ConfirmationPoCEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfirmationPoCEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfirmationPoCEvent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfirmationPoCEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmationPoCEvent.Merge(m, src)
}
func (m *ConfirmationPoCEvent) XXX_Size() int {
	return m.Size()
}
func (m *ConfirmationPoCEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmationPoCEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmationPoCEvent proto.InternalMessageInfo

func (m *ConfirmationPoCEvent) GetEpochIndex() uint64 {
	if m != nil {
		return m.EpochIndex
	}
	return 0
}

func (m *ConfirmationPoCEvent) GetEventSequence() uint64 {
	if m != nil {
		return m.EventSequence
	}
	return 0
}

func (m *ConfirmationPoCEvent) GetTriggerHeight() int64 {
	if m != nil {
		return m.TriggerHeight
	}
	return 0
}

func (m *ConfirmationPoCEvent) GetGenerationStartHeight() int64 {
	if m != nil {
		return m.GenerationStartHeight
	}
	return 0
}

func (m *ConfirmationPoCEvent) GetGenerationEndHeight() int64 {
	if m != nil {
		return m.GenerationEndHeight
	}
	return 0
}

func (m *ConfirmationPoCEvent) GetValidationStartHeight() int64 {
	if m != nil {
		return m.ValidationStartHeight
	}
	return 0
}

func (m *ConfirmationPoCEvent) GetValidationEndHeight() int64 {
	if m != nil {
		return m.ValidationEndHeight
	}
	return 0
}

func (m *ConfirmationPoCEvent) GetPhase() ConfirmationPoCPhase {
	if m != nil {
		return m.Phase
	}
	return ConfirmationPoCPhase_CONFIRMATION_POC_INACTIVE
}

func (m *ConfirmationPoCEvent) GetPocSeedBlockHash() string {
	if m != nil {
		return m.PocSeedBlockHash
	}
	return ""
}

func init() {
	proto.RegisterEnum("inference.inference.ConfirmationPoCPhase", ConfirmationPoCPhase_name, ConfirmationPoCPhase_value)
	proto.RegisterType((*ConfirmationPoCEvent)(nil), "inference.inference.ConfirmationPoCEvent")
}

func init() {
	proto.RegisterFile("inference/inference/confirmation_poc_event.proto", fileDescriptor_02c46183d02e7335)
}

var fileDescriptor_02c46183d02e7335 = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x14, 0x45, 0x33, 0x4d, 0x5a, 0xe8, 0xa0, 0x56, 0x91, 0x03, 0xc2, 0x80, 0xea, 0x06, 0x24, 0xa4,
	0x80, 0x84, 0x8b, 0x8a, 0x60, 0x8b, 0x52, 0x67, 0xa0, 0x96, 0xda, 0xd8, 0x72, 0xa2, 0x2e, 0xd8,
	0x8c, 0x9c, 0xf1, 0xab, 0x3d, 0xa2, 0x9d, 0x31, 0xf6, 0xa4, 0x2a, 0x7f, 0xc1, 0xf7, 0xf0, 0x05,
	0x6c, 0x90, 0xba, 0x64, 0x89, 0x92, 0x1f, 0xa9, 0x3c, 0x4e, 0x6b, 0x2b, 0xc9, 0xee, 0xf9, 0xde,
	0x73, 0xdf, 0xb5, 0xf4, 0x06, 0xbf, 0xe7, 0xe2, 0x1c, 0x32, 0x10, 0x0c, 0x0e, 0xaa, 0x89, 0x49,
	0x71, 0xce, 0xb3, 0xcb, 0x50, 0x71, 0x29, 0x68, 0x2a, 0x19, 0x85, 0x2b, 0x10, 0xca, 0x4e, 0x33,
	0xa9, 0xa4, 0xd1, 0xb9, 0xe7, 0xec, 0xfb, 0xe9, 0xd5, 0xdf, 0x26, 0x7e, 0xec, 0xd4, 0x52, 0xbe,
	0x74, 0x48, 0x91, 0x31, 0xf6, 0xf1, 0x23, 0x48, 0x25, 0x4b, 0x28, 0x17, 0x11, 0x5c, 0x9b, 0xa8,
	0x8b, 0x7a, 0xad, 0x00, 0x6b, 0xc9, 0x2d, 0x14, 0xe3, 0x35, 0xde, 0xd5, 0xdb, 0x69, 0x0e, 0x3f,
	0xa6, 0xc5, 0x2e, 0x73, 0x43, 0x33, 0x3b, 0x5a, 0x1d, 0x2d, 0xc4, 0x02, 0x53, 0x19, 0x8f, 0x63,
	0xc8, 0x68, 0x02, 0x3c, 0x4e, 0x94, 0xd9, 0xec, 0xa2, 0x5e, 0x33, 0xd8, 0x59, 0xa8, 0xc7, 0x5a,
	0x34, 0x3e, 0xe1, 0xa7, 0x31, 0x08, 0xc8, 0xca, 0x5f, 0xcf, 0x55, 0x98, 0xa9, 0x3b, 0xbe, 0xa5,
	0xf9, 0x27, 0x95, 0x3d, 0x2a, 0xdc, 0x45, 0xee, 0x10, 0xd7, 0x0c, 0x0a, 0x22, 0xba, 0x4b, 0x6d,
	0xea, 0x54, 0xa7, 0x32, 0x89, 0x88, 0xaa, 0xae, 0xab, 0xf0, 0x82, 0x47, 0x6b, 0xba, 0xb6, 0xca,
	0xae, 0xca, 0x5e, 0xea, 0xaa, 0xe5, 0x6a, 0x5d, 0x0f, 0xca, 0xae, 0xca, 0xac, 0xba, 0x3e, 0xe3,
	0xcd, 0x34, 0x09, 0x73, 0x30, 0x1f, 0x76, 0x51, 0x6f, 0xf7, 0xf0, 0x8d, 0xbd, 0xe6, 0x08, 0xf6,
	0xd2, 0x01, 0xfc, 0x22, 0x10, 0x94, 0x39, 0xe3, 0x1d, 0xee, 0x14, 0x87, 0xcc, 0x01, 0x22, 0x3a,
	0xb9, 0x90, 0xec, 0x3b, 0x4d, 0xc2, 0x3c, 0x31, 0xb7, 0xbb, 0xa8, 0xb7, 0x1d, 0xb4, 0x53, 0xc9,
	0x46, 0x00, 0xd1, 0x51, 0x61, 0x1c, 0x87, 0x79, 0xf2, 0xf6, 0x37, 0x5a, 0xb9, 0xa7, 0x5e, 0x67,
	0xec, 0xe1, 0x67, 0x8e, 0x37, 0xfc, 0xe2, 0x06, 0xa7, 0xfd, 0xb1, 0xeb, 0x0d, 0xa9, 0xef, 0x39,
	0xd4, 0x1d, 0xf6, 0x9d, 0xb1, 0x7b, 0x46, 0xda, 0x0d, 0xe3, 0x25, 0xde, 0x5b, 0xb1, 0xbf, 0x06,
	0x7d, 0x87, 0x50, 0x9f, 0x04, 0xae, 0x37, 0x68, 0x23, 0x63, 0x1f, 0xbf, 0x58, 0x45, 0xc8, 0x90,
	0x04, 0xfa, 0xb3, 0xbd, 0xb1, 0x16, 0x38, 0xeb, 0x9f, 0xb8, 0x83, 0x12, 0x68, 0x1a, 0x16, 0x7e,
	0xbe, 0x02, 0x38, 0xde, 0xa9, 0x7f, 0x42, 0xc6, 0x64, 0xd0, 0x6e, 0x1d, 0x79, 0x7f, 0x66, 0x16,
	0xba, 0x99, 0x59, 0xe8, 0xff, 0xcc, 0x42, 0xbf, 0xe6, 0x56, 0xe3, 0x66, 0x6e, 0x35, 0xfe, 0xcd,
	0xad, 0xc6, 0xb7, 0x8f, 0x31, 0x57, 0xc9, 0x74, 0x62, 0x33, 0x79, 0x79, 0x90, 0x66, 0x32, 0x9a,
	0x32, 0x95, 0x33, 0xbe, 0xf4, 0xfa, 0xaf, 0x6b, 0xb3, 0xfa, 0x99, 0x42, 0x3e, 0xd9, 0xd2, 0x2f,
	0xff, 0xc3, 0x6d, 0x00, 0x00, 0x00, 0xff, 0xff, 0x14, 0x9b, 0xdf, 0x18, 0x2d, 0x03, 0x00, 0x00,
}

func (m *ConfirmationPoCEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfirmationPoCEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConfirmationPoCEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PocSeedBlockHash) > 0 {
		i -= len(m.PocSeedBlockHash)
		copy(dAtA[i:], m.PocSeedBlockHash)
		i = encodeVarintConfirmationPocEvent(dAtA, i, uint64(len(m.PocSeedBlockHash)))
		i--
		dAtA[i] = 0x4a
	}
	if m.Phase != 0 {
		i = encodeVarintConfirmationPocEvent(dAtA, i, uint64(m.Phase))
		i--
		dAtA[i] = 0x40
	}
	if m.ValidationEndHeight != 0 {
		i = encodeVarintConfirmationPocEvent(dAtA, i, uint64(m.ValidationEndHeight))
		i--
		dAtA[i] = 0x38
	}
	if m.ValidationStartHeight != 0 {
		i = encodeVarintConfirmationPocEvent(dAtA, i, uint64(m.ValidationStartHeight))
		i--
		dAtA[i] = 0x30
	}
	if m.GenerationEndHeight != 0 {
		i = encodeVarintConfirmationPocEvent(dAtA, i, uint64(m.GenerationEndHeight))
		i--
		dAtA[i] = 0x28
	}
	if m.GenerationStartHeight != 0 {
		i = encodeVarintConfirmationPocEvent(dAtA, i, uint64(m.GenerationStartHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.TriggerHeight != 0 {
		i = encodeVarintConfirmationPocEvent(dAtA, i, uint64(m.TriggerHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.EventSequence != 0 {
		i = encodeVarintConfirmationPocEvent(dAtA, i, uint64(m.EventSequence))
		i--
		dAtA[i] = 0x10
	}
	if m.EpochIndex != 0 {
		i = encodeVarintConfirmationPocEvent(dAtA, i, uint64(m.EpochIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintConfirmationPocEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovConfirmationPocEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ConfirmationPoCEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochIndex != 0 {
		n += 1 + sovConfirmationPocEvent(uint64(m.EpochIndex))
	}
	if m.EventSequence != 0 {
		n += 1 + sovConfirmationPocEvent(uint64(m.EventSequence))
	}
	if m.TriggerHeight != 0 {
		n += 1 + sovConfirmationPocEvent(uint64(m.TriggerHeight))
	}
	if m.GenerationStartHeight != 0 {
		n += 1 + sovConfirmationPocEvent(uint64(m.GenerationStartHeight))
	}
	if m.GenerationEndHeight != 0 {
		n += 1 + sovConfirmationPocEvent(uint64(m.GenerationEndHeight))
	}
	if m.ValidationStartHeight != 0 {
		n += 1 + sovConfirmationPocEvent(uint64(m.ValidationStartHeight))
	}
	if m.ValidationEndHeight != 0 {
		n += 1 + sovConfirmationPocEvent(uint64(m.ValidationEndHeight))
	}
	if m.Phase != 0 {
		n += 1 + sovConfirmationPocEvent(uint64(m.Phase))
	}
	l = len(m.PocSeedBlockHash)
	if l > 0 {
		n += 1 + l + sovConfirmationPocEvent(uint64(l))
	}
	return n
}

func sovConfirmationPocEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConfirmationPocEvent(x uint64) (n int) {
	return sovConfirmationPocEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ConfirmationPoCEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfirmationPocEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfirmationPoCEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfirmationPoCEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochIndex", wireType)
			}
			m.EpochIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfirmationPocEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventSequence", wireType)
			}
			m.EventSequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfirmationPocEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EventSequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TriggerHeight", wireType)
			}
			m.TriggerHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfirmationPocEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TriggerHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenerationStartHeight", wireType)
			}
			m.GenerationStartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfirmationPocEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GenerationStartHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenerationEndHeight", wireType)
			}
			m.GenerationEndHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfirmationPocEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GenerationEndHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidationStartHeight", wireType)
			}
			m.ValidationStartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfirmationPocEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidationStartHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidationEndHeight", wireType)
			}
			m.ValidationEndHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfirmationPocEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidationEndHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Phase", wireType)
			}
			m.Phase = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfirmationPocEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Phase |= ConfirmationPoCPhase(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PocSeedBlockHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfirmationPocEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfirmationPocEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfirmationPocEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PocSeedBlockHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConfirmationPocEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfirmationPocEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConfirmationPocEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConfirmationPocEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfirmationPocEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfirmationPocEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConfirmationPocEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConfirmationPocEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConfirmationPocEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConfirmationPocEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConfirmationPocEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConfirmationPocEvent = fmt.Errorf("proto: unexpected end of group")
)
